source: site
destination: build
environment: dev

collections:
    participants:
      permalink: "/participants/:path"
      output: true
      sort_by: sort
    solutions:
      output: True
      permalink: "/solutions/:path"