source: site
destination: build

absolute: https://kth.github.io/ci-hackathon/
environment: dev

collections:
    participants:
      permalink: "/participants/:path"
      output: true
    solutions:
      output: True
      permalink: "/solutions/:path"