source: site
destination: docs

absolute: https://kth.github.io/ci-hackathon/
environment: prod

collections:
    participants:
      permalink: "/participants/:path"
      output: true
    solutions:
      output: True
      permalink: "/solutions/:path"