version: "2"
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile.prod
      context: .
    environment:
      - VIRTUAL_HOST=lights.ciart.live
      - LETSENCRYPT_HOST=lights.ciart.live
