version: "3"
services:
  organ-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app/"
      - "/usr/src/app/node_modules"
