language: elm

install:
  - npm install -g create-elm-app@3.0.6

script:
  - elm-format src/ --validate
  - npm install
  - elm-app build

deploy:
  provider: surge
  project: ./build/
  domain: elm-euterpea.surge.sh
  skip_cleanup: true
  